# Generated by Django 2.2.5 on 2019-11-19 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('codice', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'Cdl',
            },
        ),
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('anno', models.IntegerField()),
                ('corso', models.CharField(max_length=7, unique=True)),
                ('cdl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cdl')),
            ],
            options={
                'db_table': 'Corso',
            },
        ),
        migrations.CreateModel(
            name='Dipartimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('codice', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'db_table': 'Dipartimento',
            },
        ),
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Corso')),
            ],
            options={
                'db_table': 'Lezione',
            },
        ),
        migrations.CreateModel(
            name='Syllabo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descrizione', models.CharField(max_length=400)),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Corso')),
            ],
            options={
                'db_table': 'Syllabo',
            },
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('path', models.CharField(max_length=400)),
                ('tipo', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Pdf', 'Pdf')], default='Pdf', max_length=5)),
                ('lezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Lezione')),
            ],
            options={
                'db_table': 'MediaFiles',
            },
        ),
        migrations.AddField(
            model_name='cdl',
            name='dipartimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Dipartimento'),
        ),
    ]
